#!/bin/bash
set -e

# appling datacore recommended iSCSI configuration settings.
/usr/bin/ssy-configure-iscsid apply

# Reloading udev rules after adding datacore udev rules.
echo "Reloading udev rules..."
udevadm control --reload
udevadm trigger

# Restart multipath-tools after the config file was updated
echo "Restarting multipath-tools..."
systemctl restart multipath-tools

exit 0